Update patch set 1
Patch Set 1:

For some reason, this breaks compilation on Cortex-A9 (OMAP 4470): undefined reference to Clamp_S32_Opaque_D32_filter_DX_shaderproc_neon. I can't figure out why, even tried removing some of the Clamp_ prefixes to no avail. Only thing that worked was reverting this (and the next) commit.

Patch-set: 1
Reviewer: Andrei Măceș <13026@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0